export const data_perhiasan = [
    {
        nama:'Anting', codename:'AT', code:1,
        jenis: [
            {nama: 'Desy', code: 1},
            {nama: 'Desy Polos', code: 2},
            {nama: 'Gipsy', code: 3},
            {nama: 'Jepit', code: 5},
            {nama: 'Jepit Polos', code: 6},
            {nama: 'Kait', code: 7},
            {nama: 'Kait Panjang', code: 8},
            {nama: 'Kenip', code: 9},
            {nama: 'Tusuk Sate', code: 11},
        ]
    },
    {
        nama:'Giwang', codename:'GW', code:2,
        jenis: [
            {nama:'Mata Burung', code: 1},
            {nama:'Mata Desy', code: 2},
            {nama:'Pentol', code: 3},
            {nama:'Pentol Polos', code: 5},
            {nama:'Kembang', code: 6},
            {nama:'Kembang Polos', code: 7},
            {nama:'Hello Kitty', code: 8},
            {nama:'Tribal', code: 9},
            {nama:'Tribal Pasir', code: 11},
            {nama:'Tribal Ukir', code: 12},
            {nama:'1/2 Tribal', code: 13},
            {nama:'Bintang', code: 15},
            {nama:'Chanel', code: 16},
            {nama:'Segitiga', code: 17},
            {nama:'Kotak', code: 18},
            {nama:'Fashion', code: 19},
            {nama:'Panjang', code: 21},
        ]
    },
    {
        nama:'Cincin', codename:'CC', code:3,
        jenis: [
            {nama: '1/2 Rantai', code:1},
            {nama: '1/2 Pasir', code:2},
            {nama: 'Bambu Ukir', code:3},
            {nama: 'Dubai', code:5},
            {nama: 'Listring Aurel', code:6},
            {nama: 'Listring V', code:7},
            {nama: 'Patkok', code:8},
            {nama: 'Ring Polos', code:9},
            {nama: 'Stempel', code:11},
            {nama: 'Wedding', code:12},
        ]
    },
    {
        nama:'Gelang Rantai', codename:'GLR', code:5,
        jenis: [
            {nama:'Biji Lada Kombinasi', code: 1},
            {nama:'Cor', code: 2},
            {nama:'Serut', code: 3},
            {nama:'Holo', code: 5},
            {nama:'Holo Kombinasi', code: 6},
            {nama:'Holo Safir', code: 7},
            {nama:'Holo Ukir', code: 8},
            {nama:'Rantai Gepeng', code: 9},
            {nama:'Sisik Naga', code: 11},
            {nama:'Sisik Naga Double', code: 12},
            {nama:'Susun Sirih', code: 13},
        ]
    },
    {
        nama:'Gelang Bulat', codename:'GLB', code:6,
        jenis: [
            {nama: 'Cartier', code: 1},
            {nama: 'Gelombang', code: 2},
            {nama: 'Keroncong', code: 3},
            {nama: 'Fashion', code: 5},
            {nama: 'Ular', code: 6},
        ]
    },
    {
        nama:'Kalung', codename:'KL', code:7,
        jenis: [
            {nama: 'Aurel', code: 1},
            {nama: 'Balok Mini', code: 2},
            {nama: 'Biji Lada', code: 3},
            {nama: 'Biji Cabe', code: 5},
            {nama: 'Biji Padi', code: 6},
            {nama: 'Biji Timun', code: 7},
            {nama: 'Biji Timun Lilit', code: 8},
            {nama: 'Boston', code: 9},
            {nama: 'Cassandra', code: 11},
            {nama: 'Cassandra Ukir', code: 12},
            {nama: 'Gepeng', code: 13},
            {nama: 'Holo', code: 15},
            {nama: 'Holo Safir', code: 16},
            {nama: 'Holo Ukir', code: 17},
            {nama: 'Italy', code: 18},
            {nama: 'Italy Kaca', code: 19},
            {nama: 'Italy Santa', code: 21},
            {nama: 'Milano Bulat', code: 22},
            {nama: 'Milano Kotak', code: 23},
            {nama: 'Milano Gepeng', code: 25},
            {nama: 'Miyata', code: 26},
            {nama: 'Nori', code: 27},
            {nama: 'Nori Balok', code: 28},
            {nama: 'Nori Balok Ukir', code: 29},
            {nama: 'Plexi', code: 31},
            {nama: 'Rantai Gepeng', code: 32},
            {nama: 'Santa', code: 33},
            {nama: 'Sela-Seli/Lovina', code: 35},
            {nama: 'Silinder', code: 36},
            {nama: 'Tambang Lilit', code: 37},
            {nama: 'Tambang Variasi', code: 38},
        ]
    },
    {
        nama:'Liontin', codename:'Lion', code:8,
        jenis: [
            {nama: 'Chanel', code: 1},
            {nama: 'Desy', code: 2},
            {nama: 'Louis Vuitton', code: 3},
            {nama: 'Gucci', code: 5},
            {nama: 'Salib', code: 6},
            {nama: 'Batu', code: 7},
            {nama: 'Huruf', code: 8},
            {nama: 'Dubai Ukir Pohon Kelapa', code: 9},
        ]
    },
]

export const spec = [
    {
        nama: 'Warna Emas', codename: 'warna_emas', code: 1,
        jenis: [
            {nama: 'kuning', code: 1},
            {nama: 'merah', code: 2},
            {nama: 'chrome', code: 3},
            {nama: 'putih', code: 5},
        ]
    },
    {
        nama: 'Warna Mata', codename: 'warna_mata', code: 1,
        jenis: [
            {nama: 'biru transparent', codename:'mb-t', code: 11},
            {nama: 'biru muda transparent', codename: 'mbm-t', code: 12},
            {nama: 'biru tua transparent', codename: 'mbt-t', code: 13},
            {nama: 'biru kabut transparent', codename: 'mbk-t', code: 15},
            {nama: 'biru non-transparent', codename:'mb-nt', code: 16},
            {nama: 'biru muda non-transparent', codename: 'mbm-nt', code: 17},
            {nama: 'biru tua non-transparent', codename: 'mbt-nt', code: 18},
            {nama: 'coklat transparent', codename:'mc-t', code: 21},
            {nama: 'coklat muda transparent', codename: 'mcm-t', code: 22},
            {nama: 'coklat tua transparent', codename: 'mct-t', code: 23},
            {nama: 'coklat kabut transparent', codename: 'mck-t', code: 25},
            {nama: 'coklat non-transparent', codename:'mc-nt', code: 26},
            {nama: 'coklat muda non-transparent', codename: 'mcm-nt', code: 27},
            {nama: 'coklat tua non-transparent', codename: 'mct-nt', code: 28},
            {nama: 'hijau transparent', codename:'mhij-t', code: 31},
            {nama: 'hijau muda transparent', codename: 'mhij.m-t', code: 32},
            {nama: 'hijau tua transparent', codename: 'mhij.t-t', code: 33},
            {nama: 'hijau kabut transparent', codename: 'mhij.k-t', code: 35},
            {nama: 'hijau non-transparent', codename:'mhij.-nt', code: 36},
            {nama: 'hijau muda non-transparent', codename: 'mhij.m-nt', code: 37},
            {nama: 'hijau tua non-transparent', codename: 'mhij.t-nt', code: 38},
            {nama: 'hitam transparent', code: 51},
            {nama: 'hitam non-transparent', code: 52},
            {nama: 'kuning transparent', codename:'mk-t', code: 61},
            {nama: 'kuning kabut transparent', codename:'mk-t', code: 62},
            {nama: 'kuning non-transparent', codename:'mk-nt', code: 63},
            {nama: 'merah transparent', codename:'mm-t', code: 71},
            {nama: 'merah kabut transparent', codename:'mm-t', code: 72},
            {nama: 'merah non-transparent', codename:'mm-nt', code: 73},
        ]
    }
]